//
// Created by glumes on 2021/3/7.
//

#pragma once

enum FilterType{
    SHOW_TYPE,
    RBG_FILTER_TYPE,
    MIRROR_FILTER_TYPE,
    COLOR_INVERT_FILTER_TYPE,
    EXPOSURE_FILTER_TYPE,
    GAMMA_FILTER_TYPE,
    CONTRAST_FILTER_TYPE,
    HAZE_FILTER_TYPE,
};
